name = "CobblemonExtended"
author = "Camcast"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d1355bb6790e1315250dbd6444fecf73d97dc5984a934f2391e05cae27af39f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "datapack"
no-internal-hashes = false
