name = "CobblemonExtended"
author = "Camcast"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b41c24e3c207cfd9dc845f9b0e40cf199c22ee4a243ff056f834625ee2995f52"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "datapack"
no-internal-hashes = false
