name = "CobblemonExtended"
author = "Camcast"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59a02dbcf0e9e65fc015bb6c60a8db9aa5b773e604c39336ceacf48ff984571b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
