########################### EXTENSION FIELDS
# Helps eliminate repetition of sections

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

########################### SERVICES
services:

  ############################# MODPACK SERVER
  packwiz-server-cobblemonextended:
    <<: *common-keys-core
    container_name: packwiz-server-cobblemonextended
    image: ghcr.io/camcast3/packwiz:camcast3-docker@sha256:15bcb2dfc88dbcd74689ef850444df18309b4bf7bbd0e8b42ee3f709c9466ce6
    environment:
      <<: *default-tz-puid-pgid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/MinecraftInfra/cobblemonextended:/data

  packwiz-server-createexplorextended:
    <<: *common-keys-core
    container_name: packwiz-server-createexplorextended
    image: ghcr.io/camcast3/packwiz:camcast3-docker@sha256:15bcb2dfc88dbcd74689ef850444df18309b4bf7bbd0e8b42ee3f709c9466ce6
    environment:
      <<: *default-tz-puid-pgid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/MinecraftInfra/createexplorextended:/data

  packwiz-server-lobby:
    <<: *common-keys-core
    container_name: packwiz-server-lobby
    image: ghcr.io/camcast3/packwiz:camcast3-docker@sha256:15bcb2dfc88dbcd74689ef850444df18309b4bf7bbd0e8b42ee3f709c9466ce6
    environment:
      <<: *default-tz-puid-pgid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/MinecraftInfra/lobby:/data

  ############################# PROXY
  velocity:
    <<: *common-keys-core
    container_name: velocity
    image: itzg/bungeecord:java17@sha256:de225e1286a514ea69c047f2566e099180274dcc6ffdd15c4b150ca340862b66
    environment:
      TYPE: VELOCITY
      DEBUG: "true"
      ENABLE_RCON: "true"
    ports:
      - "25565:25577"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/velocity.toml:/config/velocity.toml:ro
      - $DOCKERDIR/forwarding.secret:/config/forwarding.secret:ro
      - $DOCKERDIR/appdata/velocity:/server

  ############################# MINECRAFT SERVERS
  cobblemonextended:
    <<: *common-keys-apps
    container_name: cobblemonextended
    image: itzg/minecraft-server:2024.12.1-java17-alpine@sha256:4d3c60b5d7c7276e57146af72fd982ee54a68fd3bb594dc8594d1902da0ee113
    environment:
      <<: *default-tz-puid-pgid
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SNOOPER_ENABLED: false
      MAX_PLAYERS: 10
      MODE: survival
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "FALSE"
      PACKWIZ_URL: http://packwiz-server-cobblemonextended:8080/pack.toml
      ENABLE_COMMAND_BLOCK: "true"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
    volumes:
      - $DOCKERDIR/appdata/cobblemonextended:/data
    depends_on:
     - packwiz-server-cobblemonextended

  createexplorextended:
    <<: *common-keys-apps
    container_name: createexplorextended
    image: itzg/minecraft-server:2024.12.1-java17-alpine@sha256:4d3c60b5d7c7276e57146af72fd982ee54a68fd3bb594dc8594d1902da0ee113
    environment:
      <<: *default-tz-puid-pgid
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SNOOPER_ENABLED: false
      MAX_PLAYERS: 10
      MODE: survival
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "FALSE"
      PACKWIZ_URL: http://packwiz-server-createexplorextended:8080/pack.toml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
    volumes:
      - $DOCKERDIR/appdata/createexplorextended:/data
    depends_on:
     - packwiz-server-createexplorextended

  lobby:
    <<: *common-keys-apps
    container_name: lobby
    image: itzg/minecraft-server:2024.12.1-java17-alpine@sha256:4d3c60b5d7c7276e57146af72fd982ee54a68fd3bb594dc8594d1902da0ee113
    environment:
      <<: *default-tz-puid-pgid
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SNOOPER_ENABLED: false
      MAX_PLAYERS: 10
      MODE: adventure
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "FALSE"
      PACKWIZ_URL: http://packwiz-server-lobby:8080/pack.toml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    volumes:
      - $DOCKERDIR/appdata/lobby:/data
    depends_on:
     - packwiz-server-lobby

  ############################# MONITORING

  ############################# MAINTANCE
  cobblemonextendedbackups:
    <<: *common-keys-core
    container_name: cobblemonextendedbackups
    image: itzg/mc-backup:latest@sha256:27e10f813e5331a3945a0ec217f8766a5a11f82dc7f439793383a7d3893b844a
    depends_on:
      cobblemonextended:
        condition: service_healthy
    environment:
      <<: *default-tz-puid-pgid
      BACKUP_INTERVAL: "12h"
      RCON_HOST: cobblemonextended
      INITIAL_DELAY: 0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/appdata/cobblemonextended:/data:ro
      - $DOCKERDIR/appdata/cobblemonextendedbackups:/backups
