########################### EXTENSION FIELDS
# Helps eliminate repetition of sections

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

########################### SERVICES
services:

  ############################# MODPACK SERVER
  cameronextending:
    <<: *common-keys-core
    container_name: cameronextending
    image: ghcr.io/camcast3/packwiz:camcast3-docker
    ports:
      - "8069:8080"
    environment:
      <<: *default-tz-puid-pgid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/MinecraftInfra/cobblemonextended:/data

  ############################# PROXY
  velocity:
    image: itzg/bungeecord
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    ports:
      - "25565:25577"
    volumes:
      - $DOCKERDIR/velocity.toml:/config/velocity.toml:ro
      - ./forwarding.secret:/config/forwarding.secret:ro
      - $DOCKERDIR/appdata/velocity:/server

  ############################# MINECRAFT SERVERS
  cobblemonextended:
    <<: *common-keys-apps
    container_name: cobblemonextended
    image: itzg/minecraft-server:2024.5.0-java17-alpine
    ports:
      - "25569:25565"
    environment:
      <<: *default-tz-puid-pgid
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SNOOPER_ENABLED: false
      MAX_PLAYERS: 10
      MODE: adventure
      ENABLE_WHITELIST: false
      ENABLE_ROLLING_LOGS: "true"
      PACKWIZ_URL: http://192.168.86.231:8069/pack.toml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
    volumes:
      - $DOCKERDIR/appdata/cobblemonextended:/data

  ############################# MONITORING

  ############################# MAINTANCE
