name = "CreateExploreExtended"
author = "Camcast"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac262745dee00afa309a7e073e36d3905893e62ce591803f52272be49958688f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
