name = "CreateExploreExtended"
author = "Camcast"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ffa5a9398a14a18cf81fbc9d7984a12e9d475102150f25a06c3e209f43db9f1"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
