name = "CreateExploreExtended"
author = "Camcast"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c889ad5ebcc2ed43536582cd3382d4b3166f7ff2c57c4a68bc0fd8cb91072692"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
