name = "Craft to Exile 2"
author = "negativezone"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1b85c02b8fae3d9267187bcf349a8b441bd130fe444ef1255c667ee1123119f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
