name = "Craft to Exile 2"
author = "negativezone"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ab36507875c2cc21faccce5ee595c3fbc8265293961c2f5f8e9d1d2edd6225f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
