name = "Craft to Exile 2"
author = "negativezone"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3a5d0b4e2c97edb25ab5b0b1eb2eddf4e373f20fd253b5bfd710ba672960756"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
