########################### EXTENSION FIELDS
# Helps eliminate repetition of sections

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

########################### SERVICES
services:

  ############################# MODPACK SERVER
  packwiz-server-cobblemonextended:
    <<: *common-keys-core
    container_name: packwiz-server-cobblemonextended
    image: ghcr.io/camcast3/packwiz:camcast3-docker@sha256:04182c938a7ce46c12e92005d23ce5455d48ee63820c7d692509eaab9ae8d25b
    environment:
      <<: *default-tz-puid-pgid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/MinecraftInfra/cobblemonextended:/data

  packwiz-server-createexplorextended:
    <<: *common-keys-core
    container_name: packwiz-server-createexplorextended
    image: ghcr.io/camcast3/packwiz:camcast3-docker@sha256:04182c938a7ce46c12e92005d23ce5455d48ee63820c7d692509eaab9ae8d25b
    environment:
      <<: *default-tz-puid-pgid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/MinecraftInfra/createexplorextended:/data

  packwiz-server-lobby:
    <<: *common-keys-core
    container_name: packwiz-server-lobby
    image: ghcr.io/camcast3/packwiz:camcast3-docker@sha256:04182c938a7ce46c12e92005d23ce5455d48ee63820c7d692509eaab9ae8d25b
    environment:
      <<: *default-tz-puid-pgid
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/MinecraftInfra/lobby:/data

  ############################# PROXY
  velocity:
    <<: *common-keys-core
    container_name: velocity
    image: itzg/bungeecord:java17@sha256:9436c27f4a7be5cee33e443c6f0ed3e683c59c5882e90e48ba6595090e25a6b4
    environment:
      TYPE: VELOCITY
      DEBUG: "true"
      ENABLE_RCON: "true"
    ports:
      - "25565:25577"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/velocity.toml:/config/velocity.toml:ro
      - $DOCKERDIR/forwarding.secret:/config/forwarding.secret:ro
      - $DOCKERDIR/appdata/velocity:/server

  ############################# MINECRAFT SERVERS
  cobblemonextended:
    <<: *common-keys-apps
    container_name: cobblemonextended
    image: itzg/minecraft-server:2025.10.5-java17-alpine@sha256:ecc762c91690d3f5fbfd1051aa07f173025dcaccfbf201984ddf395c21a5264f
    environment:
      <<: *default-tz-puid-pgid
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SNOOPER_ENABLED: false
      MAX_PLAYERS: 10
      MODE: survival
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "FALSE"
      PACKWIZ_URL: http://packwiz-server-cobblemonextended:8080/pack.toml
      ENABLE_COMMAND_BLOCK: "true"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
    volumes:
      - $DOCKERDIR/appdata/cobblemonextended:/data
    depends_on:
     - packwiz-server-cobblemonextended

  createexplorextended:
    <<: *common-keys-apps
    container_name: createexplorextended
    image: itzg/minecraft-server:2025.10.5-java17-alpine@sha256:ecc762c91690d3f5fbfd1051aa07f173025dcaccfbf201984ddf395c21a5264f
    environment:
      <<: *default-tz-puid-pgid
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SNOOPER_ENABLED: false
      MAX_PLAYERS: 10
      MODE: survival
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "FALSE"
      PACKWIZ_URL: http://packwiz-server-createexplorextended:8080/pack.toml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
    volumes:
      - $DOCKERDIR/appdata/createexplorextended:/data
    depends_on:
     - packwiz-server-createexplorextended

  lobby:
    <<: *common-keys-apps
    container_name: lobby
    image: itzg/minecraft-server:2025.10.5-java17-alpine@sha256:ecc762c91690d3f5fbfd1051aa07f173025dcaccfbf201984ddf395c21a5264f
    environment:
      <<: *default-tz-puid-pgid
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      SNOOPER_ENABLED: false
      MAX_PLAYERS: 10
      MODE: adventure
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "FALSE"
      PACKWIZ_URL: http://packwiz-server-lobby:8080/pack.toml
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    volumes:
      - $DOCKERDIR/appdata/lobby:/data
    depends_on:
     - packwiz-server-lobby

  ############################# MONITORING

  ############################# MAINTANCE
  cobblemonextendedbackups:
    <<: *common-keys-core
    container_name: cobblemonextendedbackups
    image: itzg/mc-backup:latest@sha256:60712c1b5759350a030aa77eac6824609a3ed42aad6ea3780e83afcd4a6204f6
    depends_on:
      cobblemonextended:
        condition: service_healthy
    environment:
      <<: *default-tz-puid-pgid
      BACKUP_INTERVAL: "12h"
      RCON_HOST: cobblemonextended
      INITIAL_DELAY: 0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - $DOCKERDIR/appdata/cobblemonextended:/data:ro
      - $DOCKERDIR/appdata/cobblemonextendedbackups:/backups
